### ISSUE TITLE
Feature: Add support for min/max/clamp

### ISSUE THREAD

**Issue by EmpireJones** [ausi/respimagelint#56]
Assuming browsers support min/max/clamp in the sizes attribute, these should be supported, like calc()

https://caniuse.com/css-math-functions

**Comment by adrian5** [comment]
I seem to have run into the same issue:

> The sizes attribute has to match the width of the image
> 
> The size of the image doesn’t match the `sizes` attribute `(max-width: 500px) calc(100vw - 30px), min(33vw, 286px)`. At a viewport of 1280x720 the image was 286 pixels wide instead of the specified 422 (-32% difference). The affected viewports are 960x540-3000x4000.

Here the trailing `min(33vw, 286px)` is the fallback that should apply to e.g. the reported `1280x720` viewport. In that case the computed `min()` value is `286px` and indeed that's the resolution the client renders at. Replacing `min(…)` with plain `286px` resolves the issue for larger screens, introducing a new one for small screens where `33vw < 286px`.

I think my rules are sound, but wanted to use this (otherwise) wonderful script as a sanity check.

**Comment by ausi** [comment]
Fixed in a95e53c24838c4d14fe726b1e1d1b39184bdfd38

Can you please verify if it works now for you?

**Comment by ausi** [comment]
> I wonder if leaning on something like [tabatkins/parse-css](https://github.com/tabatkins/parse-css) could help here

The library is great, however I was not able to use it (just) to split the `sizes` attribute into its parts as I always got a completely parsed token list that I cannot process futher and I did not find a way to serialize the tokens back into a string. It might be an option for the future to directly work with the parsed tokens, but this will require more extensive rewrite of the affected parts.

**Comment by adrian5** [comment]
> Fixed in [a95e53c](https://github.com/ausi/respimagelint/commit/a95e53c24838c4d14fe726b1e1d1b39184bdfd38)
> 
> Can you please verify if it works now for you?

That seems to have fixed it! The image now passes the rules. And when I deliberately move any of the values out of range, I get the different (expected) errors.

**Comment by adrian5** [comment]
@ausi Out of curiosity, I just checked the case reported by @alibosworth using [`calc(…)`](https://developer.mozilla.org/en-US/docs/Web/CSS/calc) and that still fails in the way he described, with `instead of the specified 0 (Infinity% difference)`, so maybe it's not full resolved yet?
