### ISSUE TITLE
JS Error (blank screen unable to complete results)

### ISSUE THREAD

**Issue by Dode123** [ausi/respimagelint#85]
I tried running respimagelint on my homepage, but get the following error:
linter.js:455 Uncaught TypeError: ((0 , _parseMedia2.default)(...) || []).forEach is not a function
    at linter.js:455:485
    at Array.forEach (<anonymous>)
    at prepareMediaQueries (linter.js:455:431)
    at exports.default (linter.js:424:136)
    at 114../linter/index (linter.js:347:315)
    at o (linter.js:1:265)
    at r (linter.js:1:431)
    at linter.js:1:460

Site URL: https://www.boardgamedungeon.net/

**Comment by ausi** [comment]
I was not able to reproduce that issue on your website. Which browser (and version) are you using?

**Comment by Dode123** [comment]
Chrome. 109.0.5414.120 (Official Build) (64-bit)

**Comment by danielbachhuber** [comment]
I see this same issue 😦 

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/36432/217600338-8a86be50-1fff-4cbc-81b7-057ecc82b2a6.png">

URL is https://jetpack.com/blog/best-lazy-load-plugin-for-wordpress/

Version 110.0.5481.77

**Comment by mcrodriguez952** [comment]
I'm experiencing the same issue. This tool was really useful to me, so I hope it can be fixed.

**Comment by mcrodriguez952** [comment]
Thanks for the suggestion, but I already tried that and I still get the
blank screen and this error in the console. I'm on the latest Chrome
(111.0.5563.64) on Mac.

[image: image.png]

**Comment by mcrodriguez952** [comment]
UPDATE: I see the bookmarklet or extension will work on some sites like https://support.safeasmilk.co/article/118-products-add-new-and-other-labels-to-your-products, but it will break on others like https://www.cnn.com/ (by break, I mean I see the progress bar, but then get the blank screen with this error in the console).
`Uncaught TypeError: ((0 , _parseMedia2.default)(...) || []).forEach is not a function at linter.js:455:485`

**Comment by peter-neumann-dev** [comment]
I can reproduce the error only for: https://www.boardgamedungeon.net/ (both with Bookmarklet and Extension in Chrome and Arc)

@mcrodriguez952 Maybe it is related to these W3C error regarding two empty `srcset` on your logo:

![Peter Neumann 2023-03-16 at 17 47 47@2x](https://user-images.githubusercontent.com/75690659/225692783-49cb82d6-9f22-4056-865c-4a237861cb27.png)

https://validator.w3.org/nu/?doc=https://www.boardgamedungeon.net/

**Comment by peter-neumann-dev** [comment]
The described error in the console appears after redirecting to https://ausi.github.io/respimagelint/linter.html (maybe good to mention it)

**Comment by v11ncent** [comment]
I am also having this same issue on Firefox, using the bookmark (not the extension).

**Comment by alan-barzilay** [comment]
I think I'm getting the same error, on firefox it shows the loading bar and upon reaching completion everything goes white and nothing happens while the console reports always the same thing in all pages: `Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data `

**Comment by woodyrew** [comment]
A little more information for Firefox, it gets to: https://ausi.github.io/respimagelint/linter.html where the browser console displays the error provided by @alan-barzilay

**Comment by KRotide** [comment]
Une solution a été trouvée ? car j'ai le même problème que ce soit avec l'extension ou le signet alors que j'ai pu l'utiliser il y a encore quelques heures.

**Comment by ausi** [comment]
The issue in Firefox seems to be related to this warning: `Partitioned cookie or storage access was provided to “https://ausi.github.io/respimagelint/store.html” because it is loaded in the third-party context and dynamic state partitioning is enabled.`

I have to rework how the data gets transferred to the report page in https://github.com/ausi/respimagelint/blob/f2008cb3070171c16759038aeb43e7806aaef285/src/collector.js#L15

**Comment by ausi** [comment]
Should be fixed in 194f75598b0fc0e26bb3166a17a3e5ecbb25f30b
Please try again

**Comment by alan-barzilay** [comment]
Fixed for me! Thanks!

**Comment by woodyrew** [comment]
Thanks, working again now in Chrome and Firefox.

**Comment by bayseek** [comment]
I'm still experiencing this bug. Chromium and Firefox; bookmarlet and addon/extension. Only on some sites.
![Selezione_012](https://github.com/ausi/respimagelint/assets/39569045/fd4b7bc5-8ad1-4d1a-a67d-458a93f2c791)

**Comment by ausi** [comment]
Should be fixed with 8d3f9891e38af906b0a10b0ca4f4f5044cebbf85
